import type { InvestmentStrategy } from "@/types/strategy";

export const DEMO_STRATEGY: InvestmentStrategy = {
  summary:
    "A balanced DeFi yield strategy allocating $10,000 across 5 battle-tested protocols on Ethereum and Arbitrum. " +
    "Prioritizes blue-chip lending and liquid staking with a stablecoin anchor for downside protection. " +
    "Projected blended APY of 8.7% with moderate risk exposure.",
  projectedApy: 8.7,
  projectedYearlyReturn: 870,
  riskAssessment:
    "Moderate risk. 40% allocated to stablecoins for capital preservation. Remaining 60% in established protocols " +
    "with audited contracts and $100M+ TVL. Primary risks: smart contract exploits, stablecoin depeg, and APY compression.",
  allocations: [
    {
      protocol: "Aave V3",
      chain: "Ethereum",
      symbol: "USDC",
      poolId: "747c1d2a-c668-4682-b9f9-296708a3dd90",
      apy: 4.2,
      tvl: 1_800_000_000,
      stablecoin: true,
      allocationAmount: 2500,
      allocationPercent: 25,
      reasoning: "Tier-1 lending protocol. USDC supply on Ethereum offers reliable base yield with minimal risk.",
      legitimacyScore: 95,
      verdict: "high_confidence",
      redFlags: [],
    },
    {
      protocol: "Lido",
      chain: "Ethereum",
      symbol: "stETH",
      poolId: "b02aa39c-54a1-4daa-ab56-65f8542b0764",
      apy: 3.6,
      tvl: 14_200_000_000,
      stablecoin: false,
      allocationAmount: 2000,
      allocationPercent: 20,
      reasoning: "Largest liquid staking protocol. stETH yield tracks Ethereum PoS rewards with deep liquidity.",
      legitimacyScore: 97,
      verdict: "high_confidence",
      redFlags: [],
    },
    {
      protocol: "Curve Finance",
      chain: "Ethereum",
      symbol: "3pool (DAI/USDC/USDT)",
      poolId: "a3a09d28-09df-4f74-b1ad-a71ea4a0a6e0",
      apy: 6.8,
      tvl: 420_000_000,
      stablecoin: true,
      allocationAmount: 1500,
      allocationPercent: 15,
      reasoning: "Blue-chip stablecoin AMM. Low IL risk with CRV gauge rewards boosting base yield.",
      legitimacyScore: 90,
      verdict: "high_confidence",
      redFlags: [],
    },
    {
      protocol: "Compound V3",
      chain: "Arbitrum",
      symbol: "USDC",
      poolId: "e49f1aec-4619-4c21-afab-c3ea95e1ece0",
      apy: 5.1,
      tvl: 350_000_000,
      stablecoin: true,
      allocationAmount: 2000,
      allocationPercent: 20,
      reasoning: "Proven lending protocol on Arbitrum L2 for lower gas costs. COMP rewards supplement base rate.",
      legitimacyScore: 92,
      verdict: "high_confidence",
      redFlags: [],
    },
    {
      protocol: "Stargate Finance",
      chain: "Arbitrum",
      symbol: "ETH",
      poolId: "f87c3c12-917d-4b38-b45a-17eab5bc3c58",
      apy: 12.4,
      tvl: 180_000_000,
      stablecoin: false,
      allocationAmount: 2000,
      allocationPercent: 20,
      reasoning: "Cross-chain bridge liquidity with STG rewards. Higher APY compensates for bridge-related risks.",
      legitimacyScore: 78,
      verdict: "moderate_confidence",
      redFlags: ["Bridge protocol — inherent cross-chain risk"],
    },
  ],
  diversificationNotes:
    "Portfolio spans 2 chains (Ethereum, Arbitrum), 5 protocols, and 3 asset types. " +
    "40% stablecoin allocation provides downside cushion. No single protocol exceeds 25% allocation.",
  warnings: [
    "Stargate carries bridge risk — monitor TVL closely for sudden outflows",
    "CRV gauge rewards may fluctuate with governance votes",
    "USDC depeg scenario would impact 60% of stablecoin-allocated capital",
  ],
  steps: [
    "Deposit 2,500 USDC into Aave V3 on Ethereum mainnet",
    "Stake 2,000 worth of ETH via Lido to receive stETH",
    "Add 1,500 in equal parts DAI/USDC/USDT to Curve 3pool and stake LP in gauge",
    "Bridge 2,000 USDC to Arbitrum and supply to Compound V3",
    "Bridge 2,000 worth of ETH to Arbitrum and deposit into Stargate ETH pool",
  ],
  generatedAt: new Date().toISOString(),
};
