import type { PortfolioSummary } from "@/types/wallet";

export const DEMO_ADDRESS = "0x742d35Cc6634C0532925a3b844Bc9e7595f2bD18";

export const DEMO_PORTFOLIO: PortfolioSummary = {
  address: DEMO_ADDRESS,
  totalValueUsd: 52_340.18,
  tokenCount: 12,
  chainCount: 4,
  tokens: [
    {
      chainId: 1,
      chainName: "Ethereum",
      symbol: "ETH",
      name: "Ether",
      balance: 5.24,
      balanceUsd: 18_340.0,
      priceUsd: 3_500.0,
      priceChange24h: 2.4,
      allocation: 35.04,
      isNative: true,
    },
    {
      chainId: 1,
      chainName: "Ethereum",
      symbol: "USDC",
      name: "USD Coin",
      balance: 8_500.0,
      balanceUsd: 8_500.0,
      priceUsd: 1.0,
      priceChange24h: 0.01,
      allocation: 16.24,
      isNative: false,
    },
    {
      chainId: 1,
      chainName: "Ethereum",
      symbol: "stETH",
      name: "Lido Staked Ether",
      balance: 2.1,
      balanceUsd: 7_350.0,
      priceUsd: 3_500.0,
      priceChange24h: 2.3,
      allocation: 14.04,
      isNative: false,
    },
    {
      chainId: 42161,
      chainName: "Arbitrum",
      symbol: "ETH",
      name: "Ether",
      balance: 1.2,
      balanceUsd: 4_200.0,
      priceUsd: 3_500.0,
      priceChange24h: 2.4,
      allocation: 8.02,
      isNative: true,
    },
    {
      chainId: 42161,
      chainName: "Arbitrum",
      symbol: "USDC",
      name: "USD Coin",
      balance: 3_200.0,
      balanceUsd: 3_200.0,
      priceUsd: 1.0,
      priceChange24h: 0.0,
      allocation: 6.11,
      isNative: false,
    },
    {
      chainId: 42161,
      chainName: "Arbitrum",
      symbol: "ARB",
      name: "Arbitrum",
      balance: 2_400.0,
      balanceUsd: 2_640.0,
      priceUsd: 1.1,
      priceChange24h: -1.8,
      allocation: 5.04,
      isNative: false,
    },
    {
      chainId: 137,
      chainName: "Polygon",
      symbol: "MATIC",
      name: "Polygon",
      balance: 3_800.0,
      balanceUsd: 2_660.0,
      priceUsd: 0.7,
      priceChange24h: -0.5,
      allocation: 5.08,
      isNative: true,
    },
    {
      chainId: 137,
      chainName: "Polygon",
      symbol: "USDT",
      name: "Tether USD",
      balance: 1_800.0,
      balanceUsd: 1_800.0,
      priceUsd: 1.0,
      priceChange24h: 0.02,
      allocation: 3.44,
      isNative: false,
    },
    {
      chainId: 10,
      chainName: "Optimism",
      symbol: "ETH",
      name: "Ether",
      balance: 0.5,
      balanceUsd: 1_750.0,
      priceUsd: 3_500.0,
      priceChange24h: 2.4,
      allocation: 3.34,
      isNative: true,
    },
    {
      chainId: 10,
      chainName: "Optimism",
      symbol: "OP",
      name: "Optimism",
      balance: 580.0,
      balanceUsd: 1_044.0,
      priceUsd: 1.8,
      priceChange24h: 3.1,
      allocation: 1.99,
      isNative: false,
    },
    {
      chainId: 1,
      chainName: "Ethereum",
      symbol: "DAI",
      name: "Dai Stablecoin",
      balance: 520.0,
      balanceUsd: 520.0,
      priceUsd: 1.0,
      priceChange24h: 0.0,
      allocation: 0.99,
      isNative: false,
    },
    {
      chainId: 1,
      chainName: "Ethereum",
      symbol: "LINK",
      name: "Chainlink",
      balance: 22.0,
      balanceUsd: 336.18,
      priceUsd: 15.28,
      priceChange24h: 1.2,
      allocation: 0.64,
      isNative: false,
    },
  ],
  chainBreakdown: [
    { chainId: 1, chainName: "Ethereum", valueUsd: 35_046.18, percentage: 66.96 },
    { chainId: 42161, chainName: "Arbitrum", valueUsd: 10_040.0, percentage: 19.18 },
    { chainId: 137, chainName: "Polygon", valueUsd: 4_460.0, percentage: 8.52 },
    { chainId: 10, chainName: "Optimism", valueUsd: 2_794.0, percentage: 5.34 },
  ],
  fetchedAt: new Date().toISOString(),
  errors: [],
};
